# Generated by Django 5.2.7 on 2025-10-24 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0002_initial'),
        ('exchange_requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerequest',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exchangerequest',
            name='offered_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offered_in_requests', to='books.book'),
        ),
        migrations.AddField(
            model_name='exchangerequest',
            name='requested_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_in_requests', to='books.book'),
        ),
        migrations.AddField(
            model_name='exchangerequest',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deal',
            name='exchange_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deal', to='exchange_requests.exchangerequest'),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewed_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_written', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='exchangerequest',
            index=models.Index(fields=['status'], name='exchange_re_status_f17bba_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangerequest',
            index=models.Index(fields=['from_user', 'to_user'], name='exchange_re_from_us_be6189_idx'),
        ),
    ]
