# Generated by Django 5.2.7 on 2025-10-24 08:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('author', models.CharField(db_index=True, max_length=255)),
                ('genre', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('book_image', models.ImageField(default='book_images/template.png', upload_to='book_images/')),
                ('condition', models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('used', 'Used')], max_length=50)),
                ('availability', models.CharField(choices=[('exchange', 'Exchange'), ('lend', 'Lend'), ('giveaway', 'Giveaway')], default='exchange', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
