# Generated by Django 5.2.7 on 2025-10-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_is_active_user_is_staff_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='User_Image',
            field=models.ImageField(default='user.png', upload_to='user_photo'),
            preserve_default=False,
        ),
    ]
