# Generated by Django 5.2.7 on 2025-10-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='User_Image',
        ),
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.ImageField(default='user.png', upload_to=''),
            preserve_default=False,
        ),
    ]
