# Generated by Django 5.2.7 on 2025-10-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_user_user_image_user_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.ImageField(default='user.png', upload_to='user_images/'),
        ),
    ]
