# Generated by Django 5.2.7 on 2025-10-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_image',
            field=models.ImageField(default='template.png', upload_to='book_images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.ImageField(default='user.png', upload_to='user_images/'),
        ),
    ]
