# Generated by Django 5.2.7 on 2025-10-13 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_user_user_image'),
        ('api', '0008_alter_user_user_image'),
    ]

    operations = [
    ]
