# Generated by Django 5.2.7 on 2025-10-13 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_merge_20251013_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.ImageField(blank=True, default='user.png', upload_to='user_images/'),
        ),
    ]
