# Generated by Django 5.2.7 on 2025-10-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_user_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.ImageField(blank=True, default='user_images/user.png', upload_to='user_images/'),
        ),
    ]
