# Generated by Django 5.2.7 on 2025-10-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_user_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=models.ImageField(default='book_images/template.png', upload_to='book_images/'),
        ),
    ]
